apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ebfks4uzp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ebfks4uzp-go 
  name: ebfks4uzp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ebfks4uzp-go 
